# Inventaire Ansible — TFE IDS/IPS & SIEM
# Adapté à l'architecture GNS3 mono-site

[dmz]
web-eurostar ansible_host=10.0.10.10 ansible_user=admin
ssh-eurostar ansible_host=10.0.10.20 ansible_user=admin
metasploitable ansible_host=10.0.10.30 ansible_user=msfadmin

[management]
suricata-sensor ansible_host=10.0.30.20 ansible_user=admin
wazuh-stack ansible_host=10.0.30.10 ansible_user=admin
ai-agent ansible_host=10.0.30.30 ansible_user=admin

[lan]
workstation-it ansible_host=10.0.20.50 ansible_user=admin
